FROM node:22-alpine

ARG PORT=3000
ARG ACCESSS_HEADER=x-forwarded-for
ARG BODY_SIZE_LIMIT=4M

ARG DB_URL

ARG PUBLIC_CLOUDFLARE_TURNSTILE_SITE_KEY
ARG CLOUDFLARE_TURNSTILE_SECRET_KEY

ARG PUBLIC_DISCORD_INVITE=http://discord.gg/NO_INVITE
ARG PUBLIC_DISCORD_OAUTH_REDIRECT_URI=http://discord.gg/NO_INVITE
ARG PUBLIC_DISCORD_CLIENT_ID
ARG DISCORD_CLIENT_SECRET

###############################################

ENV PORT=${PORT}
ENV ACCESSS_HEADER=${ACCESSS_HEADER}
ENV BODY_SIZE_LIMIT=${BODY_SIZE_LIMIT}

ENV DB_URL=${DB_URL}

ENV PUBLIC_CLOUDFLARE_TURNSTILE_SITE_KEY=${PUBLIC_CLOUDFLARE_TURNSTILE_SITE_KEY}
ENV CLOUDFLARE_TURNSTILE_SECRET_KEY=${CLOUDFLARE_TURNSTILE_SECRET_KEY}

ENV PUBLIC_DISCORD_INVITE=${PUBLIC_DISCORD_INVITE}
ENV PUBLIC_DISCORD_OAUTH_REDIRECT_URI=${PUBLIC_DISCORD_OAUTH_REDIRECT_URI}
ENV PUBLIC_DISCORD_CLIENT_ID=
ENV DISCORD_CLIENT_SECRET=

RUN mkdir -p /app/storage && chown -R node:node /app/storage

WORKDIR /app

VOLUME /app/storage

COPY package*.json .

# clean install
RUN npm ci

COPY . .

RUN npm run build

EXPOSE ${PORT}

CMD ["node", "build"]
