CREATE TABLE "server" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "server_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"last_ping_at" timestamp DEFAULT now() NOT NULL,
	"last_online_at" timestamp DEFAULT now() NOT NULL,
	"rank" integer DEFAULT 0 NOT NULL,
	"online" boolean DEFAULT true NOT NULL,
	"online_players" integer DEFAULT 0 NOT NULL,
	"max_players" integer DEFAULT 0 NOT NULL,
	"icon_url" text DEFAULT '' NOT NULL,
	"clean_motd" text DEFAULT '' NOT NULL,
	"html_motd" text DEFAULT '' NOT NULL,
	"crossplay" boolean DEFAULT false NOT NULL,
	"ip" text NOT NULL,
	"port" integer DEFAULT 25565 NOT NULL,
	"bedrock_address" text DEFAULT '' NOT NULL,
	"bedrock_port" integer DEFAULT 19132 NOT NULL,
	"votifier_enabled" boolean DEFAULT false NOT NULL,
	"votifier_address" text DEFAULT '' NOT NULL,
	"votifier_port" integer DEFAULT 8192 NOT NULL,
	"votifier_key" text DEFAULT '' NOT NULL,
	"name" text NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"banner_url" text DEFAULT '' NOT NULL,
	"website" text DEFAULT '' NOT NULL,
	"video" text DEFAULT '' NOT NULL,
	"map_url" text DEFAULT '' NOT NULL,
	"discord" text DEFAULT '' NOT NULL,
	"tags" text DEFAULT '' NOT NULL,
	"whitelisted" boolean DEFAULT false NOT NULL,
	"version_string" text DEFAULT '1.8.9' NOT NULL,
	"auto_version" boolean DEFAULT true NOT NULL,
	CONSTRAINT "server_ip_unique" UNIQUE("ip")
);
--> statement-breakpoint
CREATE TABLE "session" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"discord_access_token" text NOT NULL,
	"discord_access_token_expires_at" timestamp NOT NULL,
	"discord_refresh_token" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "session_id_unique" UNIQUE("id")
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" text PRIMARY KEY NOT NULL,
	"discord_id" text NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"last_online_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "user_id_unique" UNIQUE("id"),
	CONSTRAINT "user_discord_id_unique" UNIQUE("discord_id"),
	CONSTRAINT "user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "vote" (
	"id" text PRIMARY KEY NOT NULL,
	"server_id" integer NOT NULL,
	"ip" text NOT NULL,
	"minecraft_username" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "vote_id_unique" UNIQUE("id")
);
--> statement-breakpoint
ALTER TABLE "server" ADD CONSTRAINT "server_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vote" ADD CONSTRAINT "vote_server_id_server_id_fk" FOREIGN KEY ("server_id") REFERENCES "public"."server"("id") ON DELETE cascade ON UPDATE no action;