export const CHARS_ALLOWED_IN_USERNAME =
	'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890_';
export const MIN_SERVER_NAME_LENGTH = 5;
export const MAX_SERVER_NAME_LENGTH = 20;
export const MAX_SERVER_SLOGAN_LENGTH = 25;
export const MAX_SERVER_DESCRIPTION_LENGTH = 2000;
export const MAX_SERVER_WEBSITE_URL_LENGTH = 50;
